# Generated by Django 2.0.2 on 2018-02-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Closing_time',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Opening_time',
            new_name='opening_time',
        ),
    ]
